### PR TITLE
Use motion-gradle 2.0.0 syntax

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Comment by darinwilson** [comment]
Thanks @jjaffeux - does that syntax work in motion-gradle < 2.0?

**Comment by jjaffeux** [comment]
@darinwilson yes it should

**Comment by darinwilson** [comment]
This has been integrated as part of e3bdd0f2861283e61e4756e522f6ff1555136be2 which includes a version bump as well.

BTW, the code in the PR above didn't actually work :) - it needed the version at the end of the string, i.e.

`dependency "com.fasterxml.jackson.core:jackson-annotations:+"`

**Comment by jjaffeux** [comment]
@darinwilson That's weird, I was pretty sure it would default to + if not specified. Will look why it didnt... But it's supposed to be on gradle side, not motion-gradle related. Thx anyways.

**Pull request closed without merging**
